name: CMake

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:

  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src'
        extensions: 'h,c'

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Make
      run: cmake ./

    - name: Build Code
      run: make -j$(nproc)
