name: CMake

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:

  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang-Format-10
      run: |
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends clang-format-10

    # Keep this check seperate from the other shell commands so that we can
    # easily view just the clang-format logs in GitHub's CI log viewer.
    - name: Check Formatting
      run: /usr/bin/clang-format-10 --dry-run --style=file --Werror $(find . -name '*.c' -o -name '*.h')

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Make
      run: cmake . -Bbuild

    - name: Build Code
      run: cd build && make -j$(nproc)
