name: CMake

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:

  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src'
        extensions: 'h,c'

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Submodules
      run: git submodule update --init --recursive

    - name: Build Make
      run: cmake ./

    - name: Build Code
      run: make -j$(nproc)

    - name: Run Tests
      run: ./bin/unit_tests

    - name: Build Debian Package
      run: make -j$(nproc) package

    - name: Upload the Debian Package
      uses: actions/upload-artifact@v2.2.2
      with:
        name: tetris-mint-deb-package
        path: ./tetris-mint-*-Linux.deb
        if-no-files-found: error
